CI: 'app.merged' passes = all CI jobs do!!

diff --git a/ci/cloudbuild.app.merged.yaml b/ci/cloudbuild.app.merged.yaml
--- a/ci/cloudbuild.app.merged.yaml
+++ b/ci/cloudbuild.app.merged.yaml
@@ -32,7 +32,7 @@ steps:
   entrypoint: sh
   args: ['-c', '
     [ $PROJECT_ID != ci-builder ] || ( >&2 echo "ERROR: Please change to the deployment project: gcloud config set project <project-id>"; false ) &&
-    [ ! -z $$SENTRY_DSN ] || >&2 echo "WARN: Please provide ''SENTRY_DSN'' to enable operational monitoring."
+    [ ! -z $$SENTRY_DSN ] || >&2 echo "WARN: ''SENTRY_DSN'' missing; no operational monitoring!"
     '
   ]
   secretEnv:
@@ -45,42 +45,29 @@ steps:
     npm config set update-notifier false &&
 
     npm install &&
-    npm --prefix packages/app install
+    npm --prefix packages/app install --omit=optional
   ']
-    # Note: DO allow optional packages (for 'app'): esbuild likes them (and they are right breed, since we're within CI)
-    #
-    # npm --prefix packages/backend install &&     <-- if tests are enabled
+    # Note: '--omit=optional' does not matter, in practise (the idea was to not pull in Vite).
   env:
     - CYPRESS_INSTALL_BINARY=0
-    #- FIRESTORE_PORT=6767
-    #- FUNCTIONS_PORT=5002
-    #- DATABASE_PORT=6800    # tbd. not sure we use it?
-    #- AUTH_PORT=9100
 
   # State:
   #   - packages/app/firebase.json    has the deployment configuration (based on 'firebase.hosting.js')
 
-# DEBUG - enable if having problems with Firebase sign-in
-#
-#|- name: $_1
-#|  entrypoint: sh
-#|  args: ['-c', '
-#|    firebase use $PROJECT_ID &&
-#|
-#|    firebase apps:sdkconfig | grep -E ''^\s+".+":\s.+,'' &&
-#|    false &&
-#|
-#|    firebase apps:sdkconfig | grep -E ''^\s+".+":\s.+,'' | grep -E "projectId|appId|locationId|apiKey|authDomain|databaseURL" &&
-#|    false &&
-#|
-#|    firebase apps:sdkconfig
-#|      | grep -E ''^\s+".+":\s.+,'' | grep -E "projectId|appId|locationId|apiKey|authDomain|databaseURL"
-#|      > .capture &&
-#|
-#|    echo "export default { $$( cat .capture ) }" &&
-#|    false
-#|  ']
-#|  dir: packages/app
+# Install backend; only needed if tests are run
+- name: node:${_NODE_VER}-alpine
+  entrypoint: sh
+  args: ['-c', '
+    npm --prefix packages/backend install &&
+    (cd packages/backend && 
+      touch firebase-debug.log firestore-debug.log database-debug.log
+    )
+  ']
+  env:
+    - FIRESTORE_PORT=6767
+    - FUNCTIONS_PORT=5002
+    - DATABASE_PORT=6800    # tbd. not sure we use it?
+    - AUTH_PORT=9100
 
 # Sign in to Firebase; capture the "access values" for the project.
 #
@@ -92,44 +79,52 @@ steps:
     firebase apps:sdkconfig | grep -E ''^\s+".+":\s.+,'' | grep -E "projectId|appId|locationId|apiKey|authDomain|databaseURL"
       > .capture &&
 
-    echo "export default { $$( cat .capture ) }" > ./firebase.server.config.js
+    echo "export default { $$( cat .capture ) }" > ./firebase.config.js
   ']
   dir: packages/app
 
   # State:
-  #   - packages/app/firebase.server.config.js    has the Firebase server "access values", to be baked into the client
+  #   - packages/app/firebase.config.js    has the Firebase server "access values", to be baked into the client
 
-
-  # Test
+# Test
+#
+# Note: TO BE RETIRED, IF #102 GETS IMPLEMENTED.
 #
 # 1-to-1 from 'cloudbuild.app.yaml'.
 #
-#| TEMPORARILY DISABLED
-#|- name: docker/compose:${_DOCKER_COMPOSE_TAG}
-#|  args: ['-f', 'docker-compose.app.ci.yml', 'run', '--rm', 'emul-for-app-launched']
-#|  dir: packages/backend
-#|  env:
-#|    - CI_BUILDER_IMAGE=$_1
-#|
-#|- name: docker/compose:${_DOCKER_COMPOSE_TAG}
-#|  args: ['-f', 'docker-compose.ci.yml', 'run', 'vite-ci-launched']
-#|  dir: packages/app
-#|  env:
-#|    - CI_BUILDER_IMAGE=$_1
-#|
-#|- name: cypress/included:${_CYPRESS_TAG}
-#|  args: ['run', '--headless']
-#|  dir: packages/app
-#|  env:
-#|    - CYPRESS_baseUrl=http://vite:3002
-#|    - CYPRESS_defaultCommandTimeout=10000
+- name: docker/compose:${_DOCKER_COMPOSE_TAG}
+  args: ['-f', 'docker-compose.app.ci.yml', 'run', 'emul-for-app-launched']
+  dir: packages/backend
+  env:
+    - CI_BUILDER_IMAGE=$_1
+    - FIRESTORE_PORT=6767
+    - FUNCTIONS_PORT=5002
+    - DATABASE_PORT=6800
+    - AUTH_PORT=9100
+
+- name: docker/compose:${_DOCKER_COMPOSE_TAG}
+  args: ['-f', 'docker-compose.ci.yml', 'run', 'vite-ci-launched']
+  dir: packages/app
+  env:
+    - PORT=3002
+    - FIRESTORE_PORT=6767
+    - FUNCTIONS_PORT=5002
+    - DATABASE_PORT=6800
+    - AUTH_PORT=9100
+
+- name: cypress/included:${_CYPRESS_TAG}
+  args: ['run', '--headless']
+  dir: packages/app
+  env:
+    - CYPRESS_baseUrl=http://vite:3002
+    - CYPRESS_defaultCommandTimeout=20000
 
 # BUILD
 
 #DEBUG
 #|- name: $_1
 #|  entrypoint: sh
-#|  args: ['-c', 'cat ./firebase.server.config.js']
+#|  args: ['-c', 'cat ./firebase.config.js']
 #|  dir: packages/app
 
 - name: docker/compose:${_DOCKER_COMPOSE_TAG}
@@ -138,6 +133,7 @@ steps:
   env:
     - RELEASE=${SHORT_SHA:-0}
     #- SENTRY_SAMPLE_RATE=${_SENTRY_SAMPLE_RATE:-}
+    - FIREBASE_SERVER_CONFIG_JS=./firebase.config.js
   secretEnv:
     - SENTRY_DSN
 
@@ -152,12 +148,8 @@ steps:
 
 # --- Timeout
 #
-# Cloud Build (no tests):   1:38, 1:22
-# Cloud Build: (tests):
-#
-# OLD:
-# Cloud Build (no tests): 2:00, 1:52
-# (old CI; no tests): 2:03
+# Cloud Build (no tests):   1:38, 1:22, 1:57
+# Cloud Build: (w tests):   6:09
 #
 timeout: 400s
 
@@ -167,8 +159,7 @@ substitutions:
   _1: us-central1-docker.pkg.dev/ci-builder/builders/firebase-emulators:11.3.0
   _DOCKER_COMPOSE_TAG: 1.29.2
   _NODE_VER: "18"
-  #_CYPRESS_TAG: 9.6.0
-  #_SENTRY_SAMPLE_RATE: "1.0" # overridable by CI
+  _CYPRESS_TAG: 10.3.0
 
 # Anything baked into the front end are not really hard secrets, but let's treat them as such.
 #
