CI: app deployment works

diff --git a/ci/cloudbuild.app.merged.yaml b/ci/cloudbuild.app.merged.yaml
--- a/ci/cloudbuild.app.merged.yaml
+++ b/ci/cloudbuild.app.merged.yaml
@@ -30,13 +30,13 @@ steps:
 # Flight check
 - name: node:${_NODE_VER}-alpine
   entrypoint: sh
-  args: ['-c',
-    '[ $PROJECT_ID != ci-builder ] || ( >&2 echo "ERROR: Please change to the deployment project: gcloud config set project <project-id>"; false )
+  args: ['-c', '
+    [ $PROJECT_ID != ci-builder ] || ( >&2 echo "ERROR: Please change to the deployment project: gcloud config set project <project-id>"; false ) &&
+    [ ! -z $$SENTRY_DSN ] || >&2 echo "WARN: Please provide ''SENTRY_DSN'' to enable operational monitoring."
     '
-    #?[ ! -z $$SENTRY_DSN ] || ( >&2 echo "WARN: Please provide ''SENTRY_DSN'' to enable operational monitoring."; false )
   ]
-  #?secretEnv:
-  #?  - SENTRY_DSN
+  secretEnv:
+    - SENTRY_DSN
 
 # - Install
 - name: node:${_NODE_VER}-alpine
@@ -45,38 +45,62 @@ steps:
     npm config set update-notifier false &&
 
     npm install &&
-    npm --prefix packages/app install --omit=optional
+    npm --prefix packages/app install
   ']
+    # Note: DO allow optional packages (for 'app'): esbuild likes them (and they are right breed, since we're within CI)
+    #
     # npm --prefix packages/backend install &&     <-- if tests are enabled
-  #|env:
-  #|  - CYPRESS_INSTALL_BINARY=0
-  #|  - FIRESTORE_PORT=6767
-  #|  - FUNCTIONS_PORT=5002
-  #|  - AUTH_PORT=9100
+  env:
+    - CYPRESS_INSTALL_BINARY=0
+    #- FIRESTORE_PORT=6767
+    #- FUNCTIONS_PORT=5002
+    #- DATABASE_PORT=6800    # tbd. not sure we use it?
+    #- AUTH_PORT=9100
 
   # State:
-  # packages/app/firebase.hosting.json    has the deployment configuration
+  #   - packages/app/firebase.json    has the deployment configuration (based on 'firebase.hosting.js')
 
-# - Sign in to Firebase
-
-# Create 'firebase.live.js' based on the current project's config.
+# DEBUG - enable if having problems with Firebase sign-in
 #
-# Note: 'firebase use' is folder specific and expects: ...tbd.
+#|- name: $_1
+#|  entrypoint: sh
+#|  args: ['-c', '
+#|    firebase use $PROJECT_ID &&
+#|
+#|    firebase apps:sdkconfig | grep -E ''^\s+".+":\s.+,'' &&
+#|    false &&
+#|
+#|    firebase apps:sdkconfig | grep -E ''^\s+".+":\s.+,'' | grep -E "projectId|appId|locationId|apiKey|authDomain|databaseURL" &&
+#|    false &&
+#|
+#|    firebase apps:sdkconfig
+#|      | grep -E ''^\s+".+":\s.+,'' | grep -E "projectId|appId|locationId|apiKey|authDomain|databaseURL"
+#|      > .capture &&
+#|
+#|    echo "export default { $$( cat .capture ) }" &&
+#|    false
+#|  ']
+#|  dir: packages/app
+
+# Sign in to Firebase; capture the "access values" for the project.
 #
 - name: $_1
   entrypoint: sh
   args: ['-c', '
-    firebase --config tmp/firebase.hosting.json \
-      use $PROJECT_ID && 
+    firebase use $PROJECT_ID && 
 
-    CAPTURE=$$( firebase apps:sdkconfig
-      | grep -E ''^\s+".+":\s.+,'' | grep -E "projectId|appId|locationId|apiKey|authDomain|databaseURL"
-    ) &&
-    echo "export default { $$CAPTURE }" > ../../firebase.live.js
+    firebase apps:sdkconfig | grep -E ''^\s+".+":\s.+,'' | grep -E "projectId|appId|locationId|apiKey|authDomain|databaseURL"
+      > .capture &&
+
+    echo "export default { $$( cat .capture ) }" > ./firebase.server.config.js
   ']
   dir: packages/app
 
-# Test
+  # State:
+  #   - packages/app/firebase.server.config.js    has the Firebase server "access values", to be baked into the client
+
+
+  # Test
 #
 # 1-to-1 from 'cloudbuild.app.yaml'.
 #
@@ -100,28 +124,36 @@ steps:
 #|    - CYPRESS_baseUrl=http://vite:3002
 #|    - CYPRESS_defaultCommandTimeout=10000
 
-# Build
+# BUILD
+
+#DEBUG
+#|- name: $_1
+#|  entrypoint: sh
+#|  args: ['-c', 'cat ./firebase.server.config.js']
+#|  dir: packages/app
 
 - name: docker/compose:${_DOCKER_COMPOSE_TAG}
-  args: ['-f', 'docker-compose.tools.prod.yml', 'run', 'build']
+  args: ['-f', 'docker-compose.tools.ci.yml', 'run', 'build']
   dir: packages/app
   env:
-    - ENV=live
     - RELEASE=${SHORT_SHA:-0}
     #- SENTRY_SAMPLE_RATE=${_SENTRY_SAMPLE_RATE:-}
+  secretEnv:
+    - SENTRY_DSN
 
 # DEPLOY
 #
 - name: $_1
   entrypoint: sh
   args: ['-c', '
-    firebase --config tmp/firebase.hosting.json \
-      deploy --only hosting
+    firebase deploy --only hosting
   ']
   dir: packages/app
 
 # --- Timeout
 #
+# Cloud Build (no tests):   1:38, 1:22
+# Cloud Build: (tests):
 #
 # OLD:
 # Cloud Build (no tests): 2:00, 1:52
@@ -140,7 +172,7 @@ substitutions:
 
 # Anything baked into the front end are not really hard secrets, but let's treat them as such.
 #
-#?availableSecrets:
-#?  secretManager:
-#?    - versionName: projects/$PROJECT_NUMBER/secrets/SENTRY_DSN/versions/latest
-#?      env: 'SENTRY_DSN'
+availableSecrets:
+  secretManager:
+    - versionName: projects/$PROJECT_ID/secrets/SENTRY_DSN/versions/latest
+      env: 'SENTRY_DSN'
