Don't run tests in deployment CI scripts. Hears via Cloud Storage, whether tests had passed. Implements #102

diff --git a/ci/cloudbuild.app.merged.yaml b/ci/cloudbuild.app.merged.yaml
--- a/ci/cloudbuild.app.merged.yaml
+++ b/ci/cloudbuild.app.merged.yaml
@@ -8,12 +8,12 @@
 #   Production/staging GCP project (deploys to itself).
 #
 # Responsibility:
-#   - (maybe test,) build and deploy front-end
+#   - build and deploy front-end
 #
 # Uses images:
 #   - node:{16|18}-alpine (stock image)
-#   - firebase-emulators  (pushed to Artifact Registry)   The image also contains Firebase CLI we use for deployment
-#   - docker/compose      (stock image)
+#   - firebase-emulators  (pushed to Artifact Registry)   contains Firebase CLI we use for deployment
+#   - gsutil              (Cloud Build built-in image)
 #
 # Runtime environment:
 #   - Current directory is '/workspace/...', based on the 'dir' field
@@ -28,17 +28,23 @@
 #
 steps:
 # Flight check
-- name: node:${_NODE_VER}-alpine
+- name: gcr.io/cloud-builders/gsutil
   entrypoint: sh
   args: ['-c', '
-    [ $PROJECT_ID != ci-builder ] || ( >&2 echo "ERROR: Please change to the deployment project: gcloud config set project <project-id>"; false ) &&
-    [ ! -z $$SENTRY_DSN ] || >&2 echo "WARN: ''SENTRY_DSN'' missing; no operational monitoring!"
-    '
-  ]
+    [ $PROJECT_ID != ${_MY_BUILDER} ] || ( >&2 echo "ERROR: Please change to the deployment project: gcloud config set project <project-id>"; false ) &&
+    [ ! -z $$SENTRY_DSN ] || >&2 echo "WARN: ''SENTRY_DSN'' missing; no operational monitoring!" &&
+    
+    if [ -z ${SHORT_SHA} ]; then
+      >&2 echo "ERROR: No ''SHORT_SHA'' detected. If this is a manual run, provide one by ''--substitutions=SHORT_SHA=xxx''."; false
+    ; else
+      gsutil cat ${_GS_TOUCH_PATH}/${SHORT_SHA} ||
+        ( >&2 echo "ERROR: No evidence that tests would have passed. ''${_GS_TOUCH_PATH}/${SHORT_SHA}'' does not exist"; false )
+    ; fi
+  ']
   secretEnv:
     - SENTRY_DSN
 
-# - Install
+# Install
 - name: node:${_NODE_VER}-alpine
   entrypoint: sh
   args: ['-c', '
@@ -54,22 +60,7 @@ steps:
   # State:
   #   - packages/app/firebase.json    has the deployment configuration (based on 'firebase.hosting.js')
 
-# Install backend; only needed if tests are run
-- name: node:${_NODE_VER}-alpine
-  entrypoint: sh
-  args: ['-c', '
-    npm --prefix packages/backend install &&
-    (cd packages/backend && 
-      touch firebase-debug.log firestore-debug.log database-debug.log
-    )
-  ']
-  env:
-    - FIRESTORE_PORT=6767
-    - FUNCTIONS_PORT=5002
-    - DATABASE_PORT=6800    # tbd. not sure we use it?
-    - AUTH_PORT=9100
-
-# Sign in to Firebase; capture the "access values" for the project.
+# Sign in to Firebase; capture the "access values"
 #
 - name: $_1
   entrypoint: sh
@@ -79,54 +70,14 @@ steps:
     firebase apps:sdkconfig | grep -E ''^\s+".+":\s.+,'' | grep -E "projectId|appId|locationId|apiKey|authDomain|databaseURL"
       > .capture &&
 
-    echo "export default { $$( cat .capture ) }" > ./firebase.config.js
+    echo "export default { $$( cat .capture ) }" > firebase.config.js
   ']
   dir: packages/app
 
   # State:
   #   - packages/app/firebase.config.js    has the Firebase server "access values", to be baked into the client
 
-# Test
-#
-# Note: TO BE RETIRED, IF #102 GETS IMPLEMENTED.
-#
-# 1-to-1 from 'cloudbuild.app.yaml'.
-#
-- name: docker/compose:${_DOCKER_COMPOSE_TAG}
-  args: ['-f', 'docker-compose.app.ci.yml', 'run', 'emul-for-app-launched']
-  dir: packages/backend
-  env:
-    - CI_BUILDER_IMAGE=$_1
-    - FIRESTORE_PORT=6767
-    - FUNCTIONS_PORT=5002
-    - DATABASE_PORT=6800
-    - AUTH_PORT=9100
-
-- name: docker/compose:${_DOCKER_COMPOSE_TAG}
-  args: ['-f', 'docker-compose.ci.yml', 'run', 'vite-ci-launched']
-  dir: packages/app
-  env:
-    - PORT=3002
-    - FIRESTORE_PORT=6767
-    - FUNCTIONS_PORT=5002
-    - DATABASE_PORT=6800
-    - AUTH_PORT=9100
-
-- name: cypress/included:${_CYPRESS_TAG}
-  args: ['run', '--headless']
-  dir: packages/app
-  env:
-    - CYPRESS_baseUrl=http://vite:3002
-    - CYPRESS_defaultCommandTimeout=20000
-
-# BUILD
-
-#DEBUG
-#|- name: $_1
-#|  entrypoint: sh
-#|  args: ['-c', 'cat ./firebase.config.js']
-#|  dir: packages/app
-
+# Build
 - name: docker/compose:${_DOCKER_COMPOSE_TAG}
   args: ['-f', 'docker-compose.tools.ci.yml', 'run', 'build']
   dir: packages/app
@@ -148,8 +99,7 @@ steps:
 
 # --- Timeout
 #
-# Cloud Build (no tests):   1:38, 1:22, 1:57
-# Cloud Build: (w tests):   6:09
+# Cloud Build:  1:30
 #
 timeout: 400s
 
@@ -159,7 +109,8 @@ substitutions:
   _1: us-central1-docker.pkg.dev/ci-builder/builders/firebase-emulators:11.3.0
   _DOCKER_COMPOSE_TAG: 1.29.2
   _NODE_VER: "18"
-  _CYPRESS_TAG: 10.3.0
+  _GS_TOUCH_PATH: gs://ci-builder_cloudbuild/.passed.app    # where successful tests are marked
+  _MY_BUILDER: ci-builder
 
 # Anything baked into the front end are not really hard secrets, but let's treat them as such.
 #
diff --git a/ci/cloudbuild.app.yaml b/ci/cloudbuild.app.yaml
--- a/ci/cloudbuild.app.yaml
+++ b/ci/cloudbuild.app.yaml
@@ -11,6 +11,7 @@
 #   - node:{16|18}-alpine   (stock image)
 #   - firebase-emulators    (pushed to Artifact Registry)
 #   - docker/compose        (stock image)
+#   - gsutil                (Cloud Build built-in image)
 #
 # Runtime environment:
 #   - Current directory is '/workspace/...', based on the 'dir' field
@@ -24,15 +25,14 @@
 #   Using 'node:16' to run 'npm install' means that the packages are installed as root, and 'node_modules' is read-only
 #   to regular users (of other images). This is normally not a concern.
 
-# tbd. Remove use of 'DATABASE_PORT' - we don't need it, for testing.
-
 steps:
 # Install
 #
 - name: node:${_NODE_VER}-alpine
   entrypoint: sh
   args: ['-c', '
-    [ $PROJECT_ID == ci-builder ] || ( >&2 echo "ERROR: Please change to the ''ci-builder'' project: gcloud config set project ci-builder"; false ) &&
+    [ ! -z ${SHORT_SHA} ] || ( >&2 echo "!: No ''SHORT_SHA'' detected (this is a manual run). A successful run will NOT open doors to deployment." ) &&
+    [ $PROJECT_ID == ${_MY_BUILDER} ] || ( >&2 echo "ERROR: Please change to the ''${_MY_BUILDER}'' project: gcloud config set project ${_MY_BUILDER}"; false ) &&
 
     npm config set update-notifier false &&
 
@@ -53,7 +53,6 @@ steps:
     - CYPRESS_INSTALL_BINARY=0    # avoid downloading a GUI
     - FIRESTORE_PORT=6767
     - FUNCTIONS_PORT=5002
-    - DATABASE_PORT=6800    # tbd. not sure we use it?
     - AUTH_PORT=9100
 
   # State:
@@ -74,7 +73,6 @@ steps:
 #|    - CI_BUILDER_IMAGE=us-central1-docker.pkg.dev/${PROJECT_ID}/${_AR_FOLDER}/firebase-emulators:${_BUILDER_TAG}
 #|    - FIRESTORE_PORT=6767
 #|    - FUNCTIONS_PORT=5002
-#|    #- DATABASE_PORT=6800
 #|    - AUTH_PORT=9100
 
 # --- App
@@ -90,7 +88,6 @@ steps:
     - CI_BUILDER_IMAGE=us-central1-docker.pkg.dev/${PROJECT_ID}/${_AR_FOLDER}/firebase-emulators:${_BUILDER_TAG}
     - FIRESTORE_PORT=6767
     - FUNCTIONS_PORT=5002
-    - DATABASE_PORT=6800
     - AUTH_PORT=9100
 
 # DEBUG; TERMINAL. Enable if Vite does not launch
@@ -101,7 +98,6 @@ steps:
 #|    - PORT=3002
 #|    - FIRESTORE_PORT=6767
 #|    - FUNCTIONS_PORT=5002
-#|    - DATABASE_PORT=6800
 #|    - AUTH_PORT=9100
 
 # Launches Vite
@@ -113,7 +109,6 @@ steps:
     - PORT=3002
     - FIRESTORE_PORT=6767
     - FUNCTIONS_PORT=5002
-    - DATABASE_PORT=6800
     - AUTH_PORT=9100
 
   # State:
@@ -156,6 +151,19 @@ steps:
   args: ['run', 'lint']
   dir: packages/app
 
+#-- Pass marker
+#
+- name: gcr.io/cloud-builders/gsutil
+  entrypoint: sh
+  args: ['-c', '
+    if [ -z ${SHORT_SHA} ]; then
+      ( >&2 echo "Pass NOT MARKED to Cloud Storage since no ''SHORT_SHA'' (manual run)." )
+    ; else
+      touch _
+        && gsutil cp file://_ ${_GS_TOUCH_PATH}/${SHORT_SHA}
+    ; fi
+  ']
+
 # --- Timeout
 #
 # Cloud Build: 5:36, 5:10
@@ -173,3 +181,5 @@ substitutions:
   _CYPRESS_TAG: 10.3.0
     # https://hub.docker.com/r/cypress/included/tags?page=1&ordering=last_updated
   _AR_FOLDER: builders
+  _GS_TOUCH_PATH: gs://ci-builder_cloudbuild/.passed.app    # where successful tests are marked
+  _MY_BUILDER: ci-builder
diff --git a/ci/cloudbuild.backend.merged.yaml b/ci/cloudbuild.backend.merged.yaml
--- a/ci/cloudbuild.backend.merged.yaml
+++ b/ci/cloudbuild.backend.merged.yaml
@@ -8,12 +8,12 @@
 #   Production/staging GCP project (deploys to itself).
 #
 # Responsibility:
-#   - test and deploy backend
+#   - deploy backend
 #
 # Uses images:
 #   - node:{16|18}-alpine (stock image)
-#   - firebase-emulators  (pushed to Artifact Registry)   The image also contains Firebase CLI we use for deployment
-#   - docker/compose      (stock image)
+#   - firebase-emulators  (pushed to Artifact Registry)   contains Firebase CLI we use for deployment
+#   - gsutil              (Cloud Build built-in image)
 #
 # Runtime environment:
 #   - Current directory is '/workspace/...', based on the 'dir' field
@@ -27,12 +27,19 @@
 #     -> https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
 #
 steps:
-# Flight check: don't run deploy off general 'ci-builder'
-- name: node:${_NODE_VER}-alpine
+# Flight check
+- name: gcr.io/cloud-builders/gsutil
   entrypoint: sh
-  args: ['-c',
-    '[ $PROJECT_ID != ci-builder ] || ( >&2 echo "ERROR: Please change to the deployment project: gcloud config set project <project-id>"; false )'
-  ]
+  args: ['-c', '
+    [ $PROJECT_ID != ${_MY_BUILDER} ] || ( >&2 echo "ERROR: Please change to the deployment project: gcloud config set project <project-id>"; false ) &&
+    
+    if [ -z ${SHORT_SHA} ]; then
+      >&2 echo "ERROR: No ''SHORT_SHA'' detected. If this is a manual run, provide one by ''--substitutions=SHORT_SHA=xxx''."; false
+    ; else
+      gsutil cat ${_GS_TOUCH_PATH}/${SHORT_SHA} ||
+        ( >&2 echo "ERROR: No evidence that tests would have passed. ''${_GS_TOUCH_PATH}/${SHORT_SHA}'' does not exist"; false )
+    ; fi
+  ']
 
 # Install
 - name: node:${_NODE_VER}-alpine
@@ -43,56 +50,20 @@ steps:
     npm --prefix ../.. install &&
     npm install &&
     
-    cp tmp/firebase.ci.json ./firebase.json &&
-    cp tmp/database.rules.json . &&
-
-    touch firebase-debug.log firestore-debug.log database-debug.log
+    ln -s tmp/firebase.ci.json firebase.json &&
+    ln -s tmp/database.rules.json .
   ']
   dir: packages/backend
-    # Note: Realtime Database config is still prepared, though not used.
   env:
     - FIRESTORE_PORT=6767
     - FUNCTIONS_PORT=5002
-    #- DATABASE_PORT=6800
 
   # State:
   #   - packages/backend/functions                are installed
-  #   - packages/backend/tmp/firebase.ci.json     generated (for DC)
-  #   - packages/backend/tmp/database.rules.json  generated (for DC)
-  #   - packages/backend/firebase.json            copy for easy running of tests
-  #   - packages/backend/database.rules.json      copy for deployment
-  #   - packages/backend/{firebase|firestore|database}-debug.log      created, so DC can map them
-
-# Tests (keep similar to 'cloudbuild.backend.yaml')
-- name: docker/compose:${_DOCKER_COMPOSE_TAG}
-  args: ['-f', 'docker-compose.ci.yml', 'run', 'emul-is-healthy']
-  dir: packages/backend
-  env:
-    - CI_BUILDER_IMAGE=$_1
-    - FIRESTORE_PORT=6767
-    - FUNCTIONS_PORT=5002
-    #- DATABASE_PORT=6800
-
-#DEBUG
-# Enable this e.g. to see Cloud Function loading logs
-#|- name: node:18-alpine
-#|  entrypoint: sh
-#|  args: ['-c', '
-#|    nc -z emul 5002 && echo "5002 is up" &&
-#|    nc -z emul 6767 && echo "6767 is up" &&
-#|
-#|    echo "----" && cat ./firebase-debug.log &&
-#|    echo "----" && cat ./firestore-debug.log
-#|  ']
-#|  dir: packages/backend
-
-- name: node:18-alpine    # no warm-up, enough that we see tests pass (fns tests take ~2..3s on a cold start)
-  entrypoint: npm
-  args: ['run', 'ci:test']
-  dir: packages/backend
-  env:
-    - EMUL_HOST=emul
-    - WARM_UP_TIMEOUT=9000
+  #   - packages/backend/tmp/firebase.ci.json     generated
+  #   - packages/backend/tmp/database.rules.json  generated
+  #   - packages/backend/firebase.json            alias for deployment
+  #   - packages/backend/database.rules.json      alias for deployment
 
 # DEPLOY
 #
@@ -113,9 +84,6 @@ steps:
     # Note: The dance of picking up region id, only to inject it into the Cloud Functions source, so that Firebase can
     #   again pick it up just feels wrong. Is this really the way?
     #
-    #   Likely the author misunderstood something?? Study how Cloud Functions are deployed, to a region, and try to
-    #   simplify. PR's are welcome #contribute
-    #
     # tbd. Test that it deploys to 'us-central1'.
 
   # State:
@@ -130,7 +98,9 @@ steps:
 
 # --- Timeout
 #
-# Cloud Build: 3:26, 3:04
+# Cloud Build: 2:21
+#
+# OLD: 3:26, 3:04, 3:43
 #
 timeout: 400s
 
@@ -138,5 +108,6 @@ timeout: 400s
 #
 substitutions:
   _1: us-central1-docker.pkg.dev/ci-builder/builders/firebase-emulators:11.3.0
-  _DOCKER_COMPOSE_TAG: 1.29.2
   _NODE_VER: "18"
+  _GS_TOUCH_PATH: gs://ci-builder_cloudbuild/.passed.backend    # where successful tests are marked
+  _MY_BUILDER: ci-builder
diff --git a/ci/cloudbuild.backend.yaml b/ci/cloudbuild.backend.yaml
--- a/ci/cloudbuild.backend.yaml
+++ b/ci/cloudbuild.backend.yaml
@@ -11,6 +11,7 @@
 #   - node:{16|18}-alpine (stock image)
 #   - firebase-emulators  (pushed to Artifact Registry)
 #   - docker/compose      (stock image)
+#   - gsutil              (Cloud Build built-in image)
 #
 # Runtime environment:
 #   - Current directory is '/workspace/...', based on the 'dir' field
@@ -30,10 +31,11 @@
 steps:
 # Install
 #
-- name: node:${_NODE_VER}-alpine
+- name: node:${_NODE_VER}-alpine  # 48.8 MB (node:18-alpine) | 38.9 MB (node:16-alpine)
   entrypoint: sh
   args: ['-c', '
-    [ $PROJECT_ID == ci-builder ] || ( >&2 echo "ERROR: Please change to the ''ci-builder'' project: gcloud config set project ci-builder"; false ) &&
+    [ ! -z ${SHORT_SHA} ] || ( >&2 echo "!: No ''SHORT_SHA'' detected (this is a manual run). A successful run will NOT open doors to deployment." ) &&
+    [ $PROJECT_ID == ${_MY_BUILDER} ] || ( >&2 echo "ERROR: Please change to the ''${_MY_BUILDER}'' project: gcloud config set project ${_MY_BUILDER}"; false ) &&
 
     npm config set update-notifier false &&
 
@@ -41,7 +43,7 @@ steps:
     npm --prefix packages/backend install &&
 
     (cd packages/backend && 
-      cp tmp/firebase.ci.json ./firebase.json &&
+      ln -s tmp/firebase.ci.json ./firebase.json &&
       touch firebase-debug.log firestore-debug.log database-debug.log
     )
   ']
@@ -53,7 +55,7 @@ steps:
   # State:
   #   - packages/backend/functions/node_modules   have been populated
   #   - packages/backend/tmp/firebase.ci.json     has been created
-  #   - packages/backend/firebase.json            copy for easy running of tests
+  #   - packages/backend/firebase.json            alias for easy running of tests
   #   - packages/backend/{firebase|firestore|database}-debug.log      created, so DC can map them
 
 # DEBUG:
@@ -133,6 +135,19 @@ steps:
   args: ['run', 'lint']
   dir: packages/backend
 
+#-- Pass marker
+#
+- name: gcr.io/cloud-builders/gsutil
+  entrypoint: sh
+  args: ['-c', '
+    if [ -z ${SHORT_SHA} ]; then
+      ( >&2 echo "Pass NOT MARKED to Cloud Storage since no ''SHORT_SHA'' (manual run)." )
+    ; else
+      touch _
+        && gsutil cp file://_ ${_GS_TOUCH_PATH}/${SHORT_SHA}
+    ; fi
+  ']
+
 # --- Timeout
 #
 # Cloud Build:
@@ -148,3 +163,5 @@ substitutions:
   _NODE_VER: "18"
   _AR_FOLDER: builders
     # You may use any name, or create such a folder in AR.
+  _GS_TOUCH_PATH: gs://ci-builder_cloudbuild/.passed.backend    # where successful tests are marked
+  _MY_BUILDER: ci-builder
